-- 에버수소 홈페이지 자료실 초기 설정
-- Supabase Dashboard > SQL Editor > New query에서 전체 실행하세요.

create table if not exists public.board_posts (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 150),
  content text not null,
  file_name text,
  file_url text,
  file_path text,
  is_pinned boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.board_posts enable row level security;

create table if not exists public.board_admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.board_admins enable row level security;

create or replace function public.is_board_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.board_admins
    where user_id = (select auth.uid())
  );
$$;

revoke all on function public.is_board_admin() from public;
grant execute on function public.is_board_admin() to anon, authenticated;

drop policy if exists "Anyone can read board posts" on public.board_posts;
create policy "Anyone can read board posts"
on public.board_posts for select
to anon, authenticated
using (true);

drop policy if exists "Authenticated admins can add posts" on public.board_posts;
create policy "Authenticated admins can add posts"
on public.board_posts for insert
to authenticated
with check (public.is_board_admin());

drop policy if exists "Authenticated admins can update posts" on public.board_posts;
create policy "Authenticated admins can update posts"
on public.board_posts for update
to authenticated
using (public.is_board_admin())
with check (public.is_board_admin());

drop policy if exists "Authenticated admins can delete posts" on public.board_posts;
create policy "Authenticated admins can delete posts"
on public.board_posts for delete
to authenticated
using (public.is_board_admin());

grant select on public.board_posts to anon, authenticated;
grant insert, update, delete on public.board_posts to authenticated;
grant usage, select on sequence public.board_posts_id_seq to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('resources', 'resources', true, 20971520)
on conflict (id) do update set public = true, file_size_limit = 20971520;

drop policy if exists "Anyone can download resource files" on storage.objects;
create policy "Anyone can download resource files"
on storage.objects for select
to anon, authenticated
using (bucket_id = 'resources');

drop policy if exists "Authenticated admins can upload resource files" on storage.objects;
create policy "Authenticated admins can upload resource files"
on storage.objects for insert
to authenticated
with check (bucket_id = 'resources' and public.is_board_admin());

drop policy if exists "Authenticated admins can update resource files" on storage.objects;
create policy "Authenticated admins can update resource files"
on storage.objects for update
to authenticated
using (bucket_id = 'resources' and public.is_board_admin())
with check (bucket_id = 'resources' and public.is_board_admin());

drop policy if exists "Authenticated admins can delete resource files" on storage.objects;
create policy "Authenticated admins can delete resource files"
on storage.objects for delete
to authenticated
using (bucket_id = 'resources' and public.is_board_admin());

-- Authentication > Users에서 관리자 계정을 만든 다음 아래 예시의 이메일을
-- 실제 관리자 이메일로 바꾸고 한 번 실행하세요.
-- insert into public.board_admins (user_id)
-- select id from auth.users where email = 'admin@example.com'
-- on conflict (user_id) do nothing;
